export const lightColorVars = {
    "--x-color-0": "var(--x-color-gray-9)",
    "--x-color-1": "var(--x-color-gray-8)",
    "--x-color-2": "var(--x-color-gray-7)",
    "--x-color-3": "var(--x-color-gray-6)",
    "--x-color-4": "var(--x-color-gray-5)",
    "--x-color-5": "var(--x-color-gray-4)",
    "--x-color-6": "var(--x-color-gray-3)",
    "--x-color-7": "var(--x-color-gray-2)",
    "--x-color-8": "var(--x-color-gray-1)",
    "--x-color-9": "var(--x-color-gray-0)",

    "--x-bgcolor-0": "var(--x-color-gray-0)",
    "--x-bgcolor-1": "var(--x-color-gray-1)",
    "--x-bgcolor-2": "var(--x-color-gray-2)",
    "--x-bgcolor-3": "var(--x-color-gray-3)",
    "--x-bgcolor-4": "var(--x-color-gray-4)",
    "--x-bgcolor-5": "var(--x-color-gray-5)",
    "--x-bgcolor-6": "var(--x-color-gray-6)",
    "--x-bgcolor-7": "var(--x-color-gray-7)",
    "--x-bgcolor-8": "var(--x-color-gray-8)",
    "--x-bgcolor-9": "var(--x-color-gray-9)",
};
export const lightColorizedColorVars = {
    "--x-color-0": "var(--x-color-theme-9)",
    "--x-color-1": "var(--x-color-theme-8)",
    "--x-color-2": "var(--x-color-theme-7)",
    "--x-color-3": "var(--x-color-theme-6)",
    "--x-color-4": "var(--x-color-theme-5)",
    "--x-color-5": "var(--x-color-theme-4)",
    "--x-color-6": "var(--x-color-theme-3)",
    "--x-color-7": "var(--x-color-theme-2)",
    "--x-color-8": "var(--x-color-theme-1)",
    "--x-color-9": "var(--x-color-theme-0)",

    "--x-bgcolor-0": "var(--x-color-theme-0)",
    "--x-bgcolor-1": "var(--x-color-theme-1)",
    "--x-bgcolor-2": "var(--x-color-theme-2)",
    "--x-bgcolor-3": "var(--x-color-theme-3)",
    "--x-bgcolor-4": "var(--x-color-theme-4)",
    "--x-bgcolor-5": "var(--x-color-theme-5)",
    "--x-bgcolor-6": "var(--x-color-theme-6)",
    "--x-bgcolor-7": "var(--x-color-theme-7)",
    "--x-bgcolor-8": "var(--x-color-theme-8)",
    "--x-bgcolor-9": "var(--x-color-theme-9)",
};
